### ISSUE TITLE
publisher voting is slightly skewed

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/bat-publisher#1]
random-lib doesn't generate a perfectly uniform float distribution, see https://github.com/brave/browser-laptop/issues/6944 for details.

this has been discussed before; opening here so that it doesn't get lost.

https://github.com/brave-intl/bat-publisher/blob/master/index.js#L309

**Comment by mrose17** [comment]
@diracdeltas - is there a replacement library i can use? if so, a pointer would be nice... thanks!

**Comment by diracdeltas** [comment]
it's blocked on https://github.com/fardog/node-random-lib/pull/14 being merged

**Comment by diracdeltas** [comment]
alternatively, a small library that uses rejection sampling could be implemented in like 10 lines of js :)

**Comment by mrose17** [comment]
@fardog - your thoughts?

**Comment by fardog** [comment]
@mrose17 @diracdeltas i wrote a library for this: https://github.com/fardog/rejection-sampled-int which can be used in place if the only thing that's needed is random ints.

i haven't merged https://github.com/fardog/node-random-lib/pull/14 because i was hoping for an audit; however the original reporter hasn't had the time to perform said audit yet.

(i also hadn't decided if i liked that rewrite yet, which is neither here nor there really)

either way: probably your use of random-lib can be swapped for rejection-sampled-int if the code looks good to y'all.

**Comment by mrose17** [comment]
@fardog - thanks for the fast turn-around. i will confer with folks here... best!

**Comment by diracdeltas** [comment]
so IIRC we only need random ints between 0 and 100 inclusive (percentage values). if so, @fardog could you look over this (not-very-efficient) code and lmk if you see any problems with it:

```
const crypto = require('crypto')
function getRandomInt() {
  while (true) {
    let randomInt = crypto.randomBytes(1)[0]
    if (randomInt < 101) { return randomInt }
  }
}
```

**Comment by fardog** [comment]
@diracdeltas yep that's a cut-down version of what the synchronous call in my rejection-sampled-int library does effectively; most of the other work is around figuring out how many bytes are needed to get a number in the range you need, and read it from the buffer; a problem you won't need to solve if you only need a 0-100. this should work fine for that use case!

**edit:** just for completeness, and I haven't thought about this completely but you can probably improve efficency in this just by reading a signed int and dropping the sign bit, since you don't need that much entropy you can just ignore it

```
const crypto = require('crypto')
function getRandomint() {
  while (true) {
    const buf = crypto.randomBytes(1)
    let r = Math.abs(buf.readInt8(0))
    if (r < 101) return r
  }
}
```
should cut down on iterations

**Comment by mrose17** [comment]
@diracdeltas - the problem is that we need a float from 0.0 to 1.0, e.g., `0.8576832255382872` . can you give me a new version of the above?

thanks!

**Comment by fardog** [comment]
@mrose17 for floats, i don't believe there's any bias in https://github.com/fardog/node-random-lib, only bias is in the integer implementations.

**Comment by mrose17** [comment]
@diracdeltas - do you concur?

**Comment by fardog** [comment]
@mrose17 i mean to @diracdeltas point, if you're using a float as a percentage, you're going to end up rounding a number like `0.8576832255382872` `0.86` anyway, that rounding will introduce bias. you're better off in that case with a rejection-sampled algorithm as they suggest.

**edit:** actually sorry i'm just introducing noise here, i'll let y'all discuss how its being used; def let me know if i can provide any additional help/info though!

**Comment by mrose17** [comment]
i am having difficulty parsing this issue. @diracdeltas - the code is here: https://github.com/brave-intl/bat-publisher/blob/master/index.js#L342

i have an array, `results` of objects, each of which has a `weight`. the sum of all weights in the array is `1.0`. the `for loop` takes a number from 0.0 to 1.0 and finds where in the array it lands, by adding the weights as the array is traversed.

my question is simple: what is wrong in using `random.randomFloat()` to get the number from 0.0 to 1.0 ... thanks!

**Comment by diracdeltas** [comment]
ah, my bad. i thought this got turned into a percentage (integer) at some point but looks like it doesn't. in which case this can be closed.
